### ISSUE TITLE
Question about training hour

### ISSUE THREAD

**Issue by NoobJiahua** [epfLLM/meditron#17]
Hi I've tried to calculate the training hours by myself and get following result
![截图 2023-12-11 22-28-57](https://github.com/epfLLM/meditron/assets/75435845/8689d1bd-eb56-439d-b4f7-f70c5029c2f9)

it shows 430 hours, which is inconsistent with the 332 hours that given in your appendix A
![截图 2023-12-11 22-31-55](https://github.com/epfLLM/meditron/assets/75435845/8def7b5b-d9e6-4cb8-8b5b-d1bb0010068d)

**Comment by kylematoba** [comment]
@NoobJiahua please don't make me guess what your calculation does. If you reply with a minimal explanation of your logic, preferably also saying why this matter -- I'll take a look, but at present this is not a good github issue.
