### ISSUE TITLE
Errors with three of the scrapers

### ISSUE THREAD

**Issue by jpcorb20** [epfLLM/meditron#36]
Hello,

I was trying to scrape magic, drugs and guidelinecentral without success, while some others were fine. Any idea how to make them work? Drugs seemed to work but 0 article was in the JSONL. GuidelineCentral got some click issues. FInally, Magic printed errors for each article but one.

Thanks in advance,

**Comment by jpcorb20** [comment]
Looks like in the case of Drugs.com, it works by changing "class='ContentBox'" to "class='ddc-main-content'", and the content variable needs to be called with "content.get_attribute('innerHTML')" to get an HTML str for markdownify.

**Comment by jpcorb20** [comment]
For the GuidelineCentral, I got some issues first with the chrome driver on WSL in general and changed some options,  but it looks like the "--headless" option shouldn't be activated for this scraper to work.

**Comment by AGBonnet** [comment]
Hi @jpcorb20, 

Thanks a lot for your interest in the guidelines scraping pipeline. 

As described in the [user notice](https://github.com/epfLLM/meditron/blob/a8075e781f507bc12e824fe2ab21790ec225a198/gap-replay/guidelines/scrapers/scrapers.py#L22), these scrapers are very fickle and aren't made to withstand the dynamic nature of websites. They worked in November 2023, but there's no guarantee that they would hold in the future. 

If you'd be interested in updating the pipeline to update the scrapers, please do a pull request. We'd be grateful for your help.

**Comment by jpcorb20** [comment]
Hello @AGBonnet, thanks for your reply! Definitely, I will put a PR regarding the updates of two scrappers (Drugs and GuidelineCentral).
